# .github/workflows/flow1.yml
name: Deploy fixes to other versions with rebase main

on:
  push:
    branches:
      - 16.0

permissions: write-all

jobs:
  deploy-subversions:
    uses: Odoo-Ninjas/git-workflows/.github/workflows/deploy_to_subversions.yml@v5
    with:
      branches: 